# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    # services:
    #  mysql:
    #    image: mysql:latest
    #    # ports: 
    #    #  - 3306
    #    # needed because the mysql container does not provide a healthcheck
    #    options: >-
    #      --health-cmd "mysqladmin ping"
    #      --health-interval 10s
    #      --health-timeout 5s
    #      --health-retries 10
    #      --user=root
    #      -e "create user 'scott'@'localhost' identified by 'tiger'; create database webpy; grant all privileges on webpy.* to 'scott'@'localhost' with grant option;"
    #   postgres:
    #    image: postgres:latest
    #    env:
    #      POSTGRES_USER: postgres
    #      POSTGRES_PASSWORD: postgres
    #      POSTGRES_DB: postgres
    #    # ports:
    #    #  - 5432:5432
    #    # needed because the postgres container does not provide a healthcheck
    #    options: >-
    #      --health-cmd pg_isready
    #      --health-interval 10s
    #      --health-timeout 5s
    #      --health-retries 5
    #      -c 'create database webpy;'
    strategy:
      matrix:
        # TODO: (cclauss) add pypy3
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install codespell flake8 isort pytest
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run: isort --recursive . || true
      - run: pip install -r requirements.txt
      - run: pytest .
